In [2]:
#Assignment - Regression Assignments - SVM algorithm

In [3]:
import pandas as pd

In [4]:
dataset=pd.read_csv("insurance_pre.csv")

In [5]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [7]:
dataset.astype(int)

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [8]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [10]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [11]:
dependent=dataset[['charges']]

In [12]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [26]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [27]:
x_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]])

In [28]:
x_test

array([[ 0.89459283, -0.08863026, -0.06746417,  1.02378711, -0.50466988],
       [ 0.53757957, -0.22180837, -0.06746417, -0.97676557, -0.50466988],
       [ 0.60898222,  1.57449152,  0.76341038,  1.02378711,  1.98149332],
       ...,
       [ 1.10880078,  1.20785059, -0.89833872,  1.02378711, -0.50466988],
       [ 1.75142463,  1.34905148, -0.06746417,  1.02378711, -0.50466988],
       [ 1.60861933, -0.92299913, -0.89833872, -0.97676557, -0.50466988]])

In [20]:
x_train

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0     False       False
196    39  32.800         0     False       False
438    52  46.750         5     False       False
183    44  26.410         0     False       False
1298   33  27.455         2      True       False
...   ...     ...       ...       ...         ...
763    27  26.030         0      True       False
835    42  35.970         2      True       False
1216   40  25.080         0      True       False
559    19  35.530         0      True       False
684    33  18.500         1     False       False

[936 rows x 5 columns]

In [21]:
x_test

      age     bmi  children  sex_male  smoker_yes
578    52  30.200         1      True       False
610    47  29.370         1     False       False
569    48  40.565         2      True        True
1034   61  38.380         0      True       False
198    51  18.050         0     False       False
...   ...     ...       ...       ...         ...
1261   28  37.100         1      True       False
494    21  25.700         4      True        True
97     55  38.280         0      True       False
418    64  39.160         1      True       False
920    62  25.000         0     False       False

[402 rows x 5 columns]

In [29]:
from sklearn.svm import SVR
regressor=SVR(kernel='rbf',C=100)
regressor.fit(x_train,y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100)

In [15]:
y_pred=regressor.predict(x_test)

In [30]:
from sklearn.metrics import r2_score
r_score=r2_score(y_pred,y_test)
r_score

-14.672006812196138