In [3]:
#Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset=pd.read_csv("insurance_pre.csv")

In [5]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [6]:
dataset=pd.get_dummies(dataset)

In [7]:
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,True,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False
2,28,33.000,3,4449.46200,False,True,True,False
3,33,22.705,0,21984.47061,False,True,True,False
4,32,28.880,0,3866.85520,False,True,True,False
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,False,True,True,False
1334,18,31.920,0,2205.98080,True,False,True,False
1335,18,36.850,0,1629.83350,True,False,True,False
1336,21,25.800,0,2007.94500,True,False,True,False
1337,61,29.070,0,29141.36030,True,False,False,True

In [8]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [9]:
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,True,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False
2,28,33.000,3,4449.46200,False,True,True,False
3,33,22.705,0,21984.47061,False,True,True,False
4,32,28.880,0,3866.85520,False,True,True,False
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,False,True,True,False
1334,18,31.920,0,2205.98080,True,False,True,False
1335,18,36.850,0,1629.83350,True,False,True,False
1336,21,25.800,0,2007.94500,True,False,True,False
1337,61,29.070,0,29141.36030,True,False,False,True

In [10]:
dataset.astype(int)

      age  bmi  children  charges  sex_female  sex_male  smoker_no  smoker_yes
0      19   27         0    16884           1         0          0           1
1      18   33         1     1725           0         1          1           0
2      28   33         3     4449           0         1          1           0
3      33   22         0    21984           0         1          1           0
4      32   28         0     3866           0         1          1           0
...   ...  ...       ...      ...         ...       ...        ...         ...
1333   50   30         3    10600           0         1          1           0
1334   18   31         0     2205           1         0          1           0
1335   18   36         0     1629           1         0          1           0
1336   21   25         0     2007           1         0          1           0
1337   61   29         0    29141           1         0          0           1

[1338 rows x 8 columns]

In [11]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes'],
      dtype='object')

In [12]:
independent=dataset[['age', 'bmi', 'children','sex_female', 'sex_male',
       'smoker_no', 'smoker_yes']]

In [13]:
dependent=dataset[['charges']]

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [24]:
#Introducing Grid search
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
    'C': [10, 100, 1000, 2000, 3000],
    'gamma': ['scale', 'auto']
}
                      
grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
                      
grid.fit(x_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             verbose=3)

In [25]:
#Print best parameter after tuning
#print(grod.best_params_)

In [27]:
re=grid.cv_results_
print ("The R score value for best parameter{}:".format(grid.best_params_))

The R score value for best parameter{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}:

In [28]:
table=pd.DataFrame.from_dict(re)

In [29]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.068215,0.006676,0.015004,0.006035,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.518176,0.590247,0.473736,0.496190,0.460323,0.507734,0.045726,23
1,0.062214,0.003920,0.013402,0.005919,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.145493,0.151558,0.054750,0.086239,0.047025,0.097013,0.044105,31
2,0.068615,0.014844,0.027806,0.007084,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.017094,0.023802,-0.090154,-0.080858,-0.089650,-0.043953,0.052730,36
3,0.059976,0.006673,0.012278,0.002113,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.081543,0.096288,-0.015076,-0.007544,-0.019295,0.027183,0.050759,33
4,0.054411,0.006183,0.007801,0.001167,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.518176,0.590247,0.473736,0.496190,0.460323,0.507734,0.045726,23
5,0.046116,0.007673,0.008431,0.003107,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.150054,0.150517,0.055207,0.083278,0.045664,0.096944,0.045275,32
6,0.058204,0.006052,0.022682,0.004641,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.016896,0.023849,-0.090172,-0.080744,-0.089576,-0.043949,0.052671,35
7,0.059150,0.005025,0.012301,0.001155,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.082141,0.096133,-0.015009,-0.007927,-0.019501,0.027167,0.050925,34
8,0.051028,0.007049,0.009409,0.003256,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.595393,0.688488,0.561711,0.621904,0.560514,0.605602,0.047327,21
9,0.053285,0.006777,0.007802,0.000749,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.685792,0.688693,0.650840,0.687804,0.591088,0.660844,0.037658,13
10,0.064814,0.007781,0.023005,0.003347,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.383018,0.408677,0.261731,0.312203,0.268283,0.326782,0.059558,28
11,0.059613,0.007814,0.011890,0.002546,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.497195,0.571505,0.456907,0.477144,0.456735,0.491897,0.042530,25
12,0.052128,0.006729,0.007395,0.001482,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.595393,0.688488,0.561711,0.621904,0.560514,0.605602,0.047327,21
13,0.053077,0.007243,0.008584,0.002267,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.690192,0.687773,0.651159,0.685238,0.589667,0.660806,0.038318,14
14,0.061821,0.005801,0.022096,0.002402,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.382366,0.408917,0.261599,0.312999,0.268686,0.326913,0.059413,27
15,0.059113,0.006497,0.012047,0.002381,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.496700,0.571953,0.456794,0.475769,0.456858,0.491615,0.042783,26
16,0.067563,0.007280,0.009955,0.001912,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.605530,0.583554,0.697365,0.532563,0.681338,0.620070,0.061531,19
17,0.063688,0.006827,0.011348,0.000580,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.848856,0.809134,0.817712,0.808182,0.755841,0.807945,0.029951,5
18,0.069173,0.005375,0.022876,0.002370,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.766395,0.758282,0.712979,0.749786,0.669779,0.731444,0.035838,12
19,0.068166,0.009690,0.014267,0.002259,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.357277,0.333717,0.186948,0.073592,0.323829,0.255073,0.108568,30
20,0.064274,0.008936,0.010402,0.002417,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.605530,0.583554,0.697365,0.532563,0.681338,0.620070,0.061531,19
21,0.070373,0.006351,0.010404,0.002059,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.848833,0.808943,0.817718,0.808309,0.755874,0.807935,0.029933,6
22,0.066381,0.007874,0.022005,0.003578,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.765974,0.758330,0.712928,0.750194,0.669908,0.731467,0.035767,11
23,0.072818,0.007027,0.014602,0.000489,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.351383,0.286869,0.185340,0.271958,0.325862,0.284282,0.056885,29
24,0.077218,0.006615,0.010201,0.001938,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.660275,0.583501,0.697917,0.528950,0.655735,0.625276,0.060751,15
25,0.085417,0.008779,0.009297,0.001713,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.849483,0.806850,0.818453,0.803811,0.761269,0.807973,0.028400,4
26,0.074216,0.005077,0.024118,0.002579,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.835489,0.787376,0.804652,0.807731,0.741557,0.795361,0.031011,10
27,0.070160,0.008209,0.013519,0.002067,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-2.235805,-0.810579,-0.965960,-0.887509,-0.341879,-1.048346,0.632193,37
28,0.081236,0.004058,0.011122,0.000497,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.660275,0.583501,0.697917,0.528950,0.655735,0.625276,0.060751,15
29,0.085584,0.014133,0.009122,0.001483,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.849745,0.806905,0.818453,0.803801,0.761218,0.808024,0.028493,3
30,0.072540,0.005395,0.023806,0.003657,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.835209,0.787409,0.804632,0.807977,0.741630,0.795371,0.030930,9
31,0.064448,0.005158,0.013203,0.002787,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-2.333615,-0.799738,-0.970441,-1.571826,-0.374084,-1.209941,0.680865,38
32,0.088425,0.005882,0.010602,0.002154,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.660774,0.581383,0.697919,0.528633,0.655730,0.624888,0.061205,17
33,0.110825,0.025985,0.012403,0.000491,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.851900,0.806552,0.818549,0.803168,0.762906,0.808615,0.028620,2
34,0.077616,0.005123,0.023806,0.002316,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.845040,0.795743,0.818166,0.814178,0.750574,0.804740,0.031332,7
35,0.068816,0.003868,0.014203,0.001601,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-6.205404,-5.659432,-5.586891,-4.675140,-4.084192,-5.242212,0.759368,40
36,0.089219,0.002787,0.010203,0.001940,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.660774,0.581383,0.697919,0.528633,0.655730,0.624888,0.061205,17
37,0.097260,0.022142,0.009827,0.002817,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.851928,0.806523,0.818566,0.803173,0.762927,0.808623,0.028623,1
38,0.081818,0.007084,0.022231,0.003334,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.844757,0.795777,0.818152,0.814232,0.750640,0.804712,0.031236,8
39,0.070368,0.004885,0.011293,0.002483,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-5.514020,-5.522878,-5.605681,-2.941765,-3.530519,-4.622973,1.147992,39